import { ValidationError } from './Errors';

export interface ActionChecklistItem {
  id: string;
  label: string;
  category: string;
  completed: boolean;
}

export interface LawyerChecklist {
  questionsToAsk: string[];
  documentsToBring: string[];
  importantDeadlines: string[];
  keyConcerns: string[];
  clarificationAreas: string[];
}

export interface LegalBriefingProps {
  id: string;
  userId: string;
  documentId: string;
  documentTitle: string;
  conciseSummary: string;
  lawyerChecklist: LawyerChecklist;
  actionChecklist: ActionChecklistItem[];
  createdAt: Date;
  updatedAt: Date;
}

export class LegalBriefing {
  private props: LegalBriefingProps;

  constructor(props: LegalBriefingProps) {
    if (!props.id || props.id.trim().length === 0) {
      throw new ValidationError('Briefing ID is required');
    }
    if (!props.userId || props.userId.trim().length === 0) {
      throw new ValidationError('User ID is required');
    }
    if (!props.documentId || props.documentId.trim().length === 0) {
      throw new ValidationError('Document ID is required');
    }
    if (!props.conciseSummary || props.conciseSummary.trim().length === 0) {
      throw new ValidationError('Concise summary is required');
    }

    this.props = {
      ...props,
      actionChecklist: props.actionChecklist || [],
    };
  }

  public get id(): string {
    return this.props.id;
  }

  public get userId(): string {
    return this.props.userId;
  }

  public get documentId(): string {
    return this.props.documentId;
  }

  public get documentTitle(): string {
    return this.props.documentTitle;
  }

  public get conciseSummary(): string {
    return this.props.conciseSummary;
  }

  public get lawyerChecklist(): LawyerChecklist {
    return { ...this.props.lawyerChecklist };
  }

  public get actionChecklist(): ActionChecklistItem[] {
    return [...this.props.actionChecklist];
  }

  public get createdAt(): Date {
    return this.props.createdAt;
  }

  public get updatedAt(): Date {
    return this.props.updatedAt;
  }

  public toggleChecklistItem(itemId: string, completed?: boolean): void {
    const item = this.props.actionChecklist.find((i) => i.id === itemId);
    if (!item) {
      throw new ValidationError(`Checklist item with id ${itemId} not found`);
    }
    item.completed = completed !== undefined ? completed : !item.completed;
    this.props.updatedAt = new Date();
  }

  public isOwnedBy(userId: string): boolean {
    return this.props.userId === userId;
  }

  public toMarkdown(): string {
    const lines: string[] = [];
    lines.push(`# Legal Briefing: ${this.props.documentTitle}`);
    lines.push(`\n*Generated by LegalLens for informational assistance — Not formal legal advice.*\n`);
    lines.push(`## Concise Summary\n${this.props.conciseSummary}\n`);

    lines.push(`## Lawyer Consultation Preparation`);
    lines.push(`### Questions to Ask Your Lawyer`);
    this.props.lawyerChecklist.questionsToAsk.forEach((q) => lines.push(`- [ ] ${q}`));

    lines.push(`\n### Documents to Bring`);
    this.props.lawyerChecklist.documentsToBring.forEach((d) => lines.push(`- [ ] ${d}`));

    lines.push(`\n### Key Concerns Identified`);
    this.props.lawyerChecklist.keyConcerns.forEach((c) => lines.push(`- ⚠️ ${c}`));

    lines.push(`\n### Important Deadlines`);
    this.props.lawyerChecklist.importantDeadlines.forEach((dl) => lines.push(`- 📅 ${dl}`));

    lines.push(`\n## Action Checklist`);
    this.props.actionChecklist.forEach((item) => {
      lines.push(`- [${item.completed ? 'x' : ' '}] (${item.category}) ${item.label}`);
    });

    return lines.join('\n');
  }

  public toJSON(): Record<string, unknown> {
    return {
      id: this.props.id,
      userId: this.props.userId,
      documentId: this.props.documentId,
      documentTitle: this.props.documentTitle,
      conciseSummary: this.props.conciseSummary,
      lawyerChecklist: this.props.lawyerChecklist,
      actionChecklist: this.props.actionChecklist,
      createdAt: this.props.createdAt.toISOString(),
      updatedAt: this.props.updatedAt.toISOString(),
    };
  }
}
